### ISSUE TITLE
Cache purge Error 1014 

### ISSUE THREAD

**Issue by romanoffs** [cloudflare/cloudflare-php#61] opened 2018-08-17 17:12 UTC
My request : 
        $zones->cachePurge($zoneID, [$url], []);

But the response contains this error, what's the problem?

{"success":false,"errors":[{"code":1014,"message":"\"files\", \"tags\", or \"hosts\" must be an array"}],"messages":[]," (truncated...)

**Comment by garrettgalow** [comment] 2018-08-17 17:27
this looks to be a dupe of #59 or at least related

**Comment by ljoseppi** [comment] 2018-08-21 14:16
I've replaced lines 167-170 of file Endpoints/Zones.php with:
`$options = [];
 $files AND $options['files'] = $files;
 $tags AND $options['tags'] = $tags;`

**Closed** 2018-08-28 14:06 UTC

**Comment by emgk** [comment] 2018-09-21 05:10
Hey @IcyApril I'm using call `https://api.cloudflare.com/client/v4/` endpoint and still getting the same error.
